#i Alias de directorios xenéricos
alias up='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias home='cd $HOME; ls'
alias documentos='cd $(xdg-user-dir DOCUMENTS); ls'
alias doc='cd $(xdg-user-dir DOCUMENTS); ls'
alias descargas='cd $(xdg-user-dir DOWNLOAD); ls'
alias des='cd $(xdg-user-dir DOWNLOAD); ls'
alias musica='cd $(xdg-user-dir MUSIC); ls'
alias imaxes='cd $(xdg-user-dir PICTURES); ls'
alias imx='cd $(xdg-user-dir PICTURES); ls'
alias plantillas='cd $(xdg-user-dir TEMPLATES); ls'
alias videos='cd $(xdg-user-dir VIDEOS); ls'
