# Alias útiles
alias vi='vim'
alias svim='sudo vim'
alias ngrok='ngrok http 80'
alias server='sudo python -m http.server 80'
alias extip='curl ifconfig.me/ip'
alias reload='source $HOME/.bashrc'
alias bashrc='$EDITOR $HOME/.bashrc && source $HOME/.bashrc'
alias bashpr='$EDITOR $HOME/.bash_profile && source $HOME/.bash_profile'
alias bashdr='cd $HOME/.bashrc.d/; ls'
