#!/bin/bash
# -*- ENCODING: UTF-8 -*-
# bashrc.d: https://github.com/barcia/.bashrc.d
# ln $HOME/.bashrc.d/bashrc $HOME/.bashrc

BASHRC_DIR="$HOME/.bashrc.d"

. $BASHRC_DIR/settings.sh
. $BASHRC_DIR/user.sh
. $BASHRC_DIR/alias.sh

if [ -f $HOME/.scripts/scripts-alias.sh ]; then
    . $HOME/.scripts/scripts-alias.sh
fi

for i in $(ls $BASHRC_DIR/functions/)
do
  . $BASHRC_DIR/functions/$i
done
